FROM selenium/standalone-chrome:3.141.59-palladium
USER root 
WORKDIR /opt/test 
RUN apt update && apt install -y \
  python3-pip \
  vim \
  git \
  tree 
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt 
#COPY ../ .  #use "-v" mount instead of copy 
#CMD [ "python3", "scripts/run_test_suite.py" ]
